apiVersion: v1
kind: Secret
metadata:
    name: nzbget-secrets
type: Opaque
stringData:
    newshosting-password: ENC[AES256_GCM,data:APLVQeoNmmLr86pmxAt+MVSHBw==,iv:AlpK39XSd31KoBxh3AO44JBj7WXavr/7jB7WeHiraGs=,tag:l4n/mzUOReSHPhX43F/iUw==,type:str]
    nzbget-password: ENC[AES256_GCM,data:eM9bnr8=,iv:G1pBTvsalersi1wN5aj41tCeF1TW3DNBnhAvfy+r0RA=,tag:KbtFPv6QGPpH/EEQXTZk0g==,type:str]
sops:
    age:
        - recipient: age1z2njmd0924r7k73djmkhg4h9vyg9nnfslm7fpr23ktlksw65z5mq0yels5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SWNtN0Naa25OZUNwbkVk
            MXlFdHZNMEpXUUZ4MmlpdkhvYk5XSkdFdEJjClBNTlJLOFlKRDlkcEE4bW41c3Ri
            R0tSZW5nWXhzakpmdUNtdW81ZmtIcVUKLS0tIGU4UlBseVY4MENzVzBmaVJTQndj
            U2ZHT0hzY3pqRjdIRllVZ0VuRENZUDQKKAXEn9ts/dv6ShlnbAavt91IgMvLxK64
            sBvn2zugvf+9uuiRveoTHs3x4o6p06lQW+XoA9wKrmGZajmdw0Do+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T18:44:52Z"
    mac: ENC[AES256_GCM,data:3eWfJyG+PT1IPZOnL3Bl7XLqJRHFhNNLFZui1Be5I2vquGpl+78xk/RxmEq4PDZxOIFgneXW5xD3vgws+wIq6wKY+esmCFL5XOE+oonnEAkm1ccRv6mrtRMg6Tza0Psz66H0eUBeUYYs30o+NNsa6IEbFGOLp4DlwU4Ehs41oVo=,iv:k7VRzUSB8P9C+wq0BAa69y9TxjQjb2eQRdJ82Gj+aGs=,tag:90FKmNV2y4MjcnCmqLX7rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: buildarr-secrets
type: Opaque
stringData:
    nzbgeek-api-key: ENC[AES256_GCM,data:blbiV0PfdloI1fuU/xD87xmNgukzjsL3I1wgWMgXqoc=,iv:ZH1MbHE7CHSlA5exUUZVQnYSlAbYqK/mEJWkNjPrsaw=,tag:VA+oBhQt51glDOiYPtjwsQ==,type:str]
    nzbget-password: ENC[AES256_GCM,data:vSfAXOo=,iv:Use5f1gB65aqDKYv6+fygUBRZBNOm3o0+jIedkjnJto=,tag:A8gKnVMdMwrVHr1ReUUtLQ==,type:str]
sops:
    age:
        - recipient: age1z2njmd0924r7k73djmkhg4h9vyg9nnfslm7fpr23ktlksw65z5mq0yels5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SWNtN0Naa25OZUNwbkVk
            MXlFdHZNMEpXUUZ4MmlpdkhvYk5XSkdFdEJjClBNTlJLOFlKRDlkcEE4bW41c3Ri
            R0tSZW5nWXhzakpmdUNtdW81ZmtIcVUKLS0tIGU4UlBseVY4MENzVzBmaVJTQndj
            U2ZHT0hzY3pqRjdIRllVZ0VuRENZUDQKKAXEn9ts/dv6ShlnbAavt91IgMvLxK64
            sBvn2zugvf+9uuiRveoTHs3x4o6p06lQW+XoA9wKrmGZajmdw0Do+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T18:44:52Z"
    mac: ENC[AES256_GCM,data:3eWfJyG+PT1IPZOnL3Bl7XLqJRHFhNNLFZui1Be5I2vquGpl+78xk/RxmEq4PDZxOIFgneXW5xD3vgws+wIq6wKY+esmCFL5XOE+oonnEAkm1ccRv6mrtRMg6Tza0Psz66H0eUBeUYYs30o+NNsa6IEbFGOLp4DlwU4Ehs41oVo=,iv:k7VRzUSB8P9C+wq0BAa69y9TxjQjb2eQRdJ82Gj+aGs=,tag:90FKmNV2y4MjcnCmqLX7rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
