apiVersion: v1
kind: Secret
metadata:
    name: nzbget-secrets
type: Opaque
stringData:
    newshosting-password: ENC[AES256_GCM,data:APLVQeoNmmLr86pmxAt+MVSHBw==,iv:AlpK39XSd31KoBxh3AO44JBj7WXavr/7jB7WeHiraGs=,tag:l4n/mzUOReSHPhX43F/iUw==,type:str]
    nzbget-password: ENC[AES256_GCM,data:vSfAXOo=,iv:Use5f1gB65aqDKYv6+fygUBRZBNOm3o0+jIedkjnJto=,tag:A8gKnVMdMwrVHr1ReUUtLQ==,type:str]
sops:
    age:
        - recipient: age1z2njmd0924r7k73djmkhg4h9vyg9nnfslm7fpr23ktlksw65z5mq0yels5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SWNtN0Naa25OZUNwbkVk
            MXlFdHZNMEpXUUZ4MmlpdkhvYk5XSkdFdEJjClBNTlJLOFlKRDlkcEE4bW41c3Ri
            R0tSZW5nWXhzakpmdUNtdW81ZmtIcVUKLS0tIGU4UlBseVY4MENzVzBmaVJTQndj
            U2ZHT0hzY3pqRjdIRllVZ0VuRENZUDQKKAXEn9ts/dv6ShlnbAavt91IgMvLxK64
            sBvn2zugvf+9uuiRveoTHs3x4o6p06lQW+XoA9wKrmGZajmdw0Do+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T19:40:30Z"
    mac: ENC[AES256_GCM,data:RmXVWaCx7leTVJU1iF/rPhU3ZlOQDX3DwJqCa5V+SJl9mFYzwfox3YBTjcg9RctEc3jewu1Ec58Q1G7TXpvPF57qIk2f6LehFWbDwINpt8FClX8JXnnR5LK/EQCl4/I0v3UZoi4wBhJZhFnofo+Dg+UflkHMAAo4e9gzp/Nz31Y=,iv:0v/waYC9zzdnvFpCSszpJy2czfoXDbA1k3fkk2lTb0c=,tag:BhwlBiv2vMZGlApi0to5/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: buildarr-secrets
type: Opaque
stringData:
    nzbgeek-api-key: ENC[AES256_GCM,data:blbiV0PfdloI1fuU/xD87xmNgukzjsL3I1wgWMgXqoc=,iv:ZH1MbHE7CHSlA5exUUZVQnYSlAbYqK/mEJWkNjPrsaw=,tag:VA+oBhQt51glDOiYPtjwsQ==,type:str]
    nzbget-password: ENC[AES256_GCM,data:vSfAXOo=,iv:Use5f1gB65aqDKYv6+fygUBRZBNOm3o0+jIedkjnJto=,tag:A8gKnVMdMwrVHr1ReUUtLQ==,type:str]
    prowlarr-api-key: ENC[AES256_GCM,data:MxKzYJnVhD1s8ymUCjHXHZCkFy/WNKYkZH6Kt2x2GLY=,iv:IxlKZp02DMELprKy6A6bvcaRpWnmxzYQI2nGbsFfV9M=,tag:oaJm3PyWD6q9X5nkccp9rw==,type:str]
    sonarr-api-key: ENC[AES256_GCM,data:vIw0n9Rho/DL15Bif88JLx8XQGVJXONYB5crNjlYXyc=,iv:0Wl3ToigsEBXy/K2WoLSSwikJORWhFvYEV2cefqqcxw=,tag:gz6/D3ScRvS2NHPJuT8zYw==,type:str]
    radarr-api-key: ENC[AES256_GCM,data:qE6YOo0msDN2+xsJrQfHiOUgJwoUg47rdAQISuriTIQ=,iv:/3O6AXas9qCDeo1VfgFeEhTJSarOH0Lc3+Z78+wqX5g=,tag:D8ZZkUjKYmhwXWwrUOdd0g==,type:str]
sops:
    age:
        - recipient: age1z2njmd0924r7k73djmkhg4h9vyg9nnfslm7fpr23ktlksw65z5mq0yels5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SWNtN0Naa25OZUNwbkVk
            MXlFdHZNMEpXUUZ4MmlpdkhvYk5XSkdFdEJjClBNTlJLOFlKRDlkcEE4bW41c3Ri
            R0tSZW5nWXhzakpmdUNtdW81ZmtIcVUKLS0tIGU4UlBseVY4MENzVzBmaVJTQndj
            U2ZHT0hzY3pqRjdIRllVZ0VuRENZUDQKKAXEn9ts/dv6ShlnbAavt91IgMvLxK64
            sBvn2zugvf+9uuiRveoTHs3x4o6p06lQW+XoA9wKrmGZajmdw0Do+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T19:40:30Z"
    mac: ENC[AES256_GCM,data:RmXVWaCx7leTVJU1iF/rPhU3ZlOQDX3DwJqCa5V+SJl9mFYzwfox3YBTjcg9RctEc3jewu1Ec58Q1G7TXpvPF57qIk2f6LehFWbDwINpt8FClX8JXnnR5LK/EQCl4/I0v3UZoi4wBhJZhFnofo+Dg+UflkHMAAo4e9gzp/Nz31Y=,iv:0v/waYC9zzdnvFpCSszpJy2czfoXDbA1k3fkk2lTb0c=,tag:BhwlBiv2vMZGlApi0to5/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
