apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-config
data:
  config.yml: |
    upstreams:
      groups:
        default:
          - https://dns.cloudflare.com/dns-query
          - https://dns.google/dns-query
    customDNS:
      mapping:
        # Nodes
        pi1.internal.heidi.codes: 192.168.1.21
        pi2.internal.heidi.codes: 192.168.1.22
        pi3.internal.heidi.codes: 192.168.1.23
        # Cluster services (Traefik)
        cluster1.internal.heidi.codes: 192.168.1.100
      zone: |
        $ORIGIN cluster1.internal.heidi.codes.
        * A 192.168.1.100
    ports:
      dns: 53
      http: 4000
    log:
      level: info
