apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: metallb-system
spec:
  type: ClusterIP
  selector:
    app: test
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: metallb-system
  labels:
    app: test
spec:
  containers:
    - name: nginx
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: test-route
  namespace: metallb-system
spec:
  parentRefs:
    - name: traefik
      namespace: traefik
      kind: Gateway
  hostnames:
    - "test.example.com"
  rules:
    - backendRefs:
        - name: test-service
          port: 80
