apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:2hZ2Y5v3paRzRf5iW6bt2HfskHhyfqNqzdiZ6+NZg8RgMwTkuxKxYg==,iv:2X61iFfKgLwa9a1RB8Vi0cxe9YxqqmXYspXyjqXvNHs=,tag:pydd1GW+2O6fDbl4Xhyd6w==,type:str]
sops:
    age:
        - recipient: age1z2njmd0924r7k73djmkhg4h9vyg9nnfslm7fpr23ktlksw65z5mq0yels5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaURobUYxWDB6V3NrM2ZX
            bXJadjhOV3UyVUlZL3Zkd2dOb3NGV0RoVWs0Ck1uemtsTmpVNFZ2M3NYTHhPdXk4
            M0lISDJjNFZrTFBGZ1dHT2JCMFJDWEEKLS0tIE5aeXNldlF5SFhtUUtqdU1lRGtX
            TXNPWGJYc3V3QUxhNDlETXdQNi95VlEKpr7YNB/VsyHG/GnRLBR8J9IcCh8OEKFv
            pG6i94ltXfFFvE65e/PaMnD+KBhtDBbc8ZMXdrki/zukjEDJOaH1Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T23:15:43Z"
    mac: ENC[AES256_GCM,data:ZPoLkSnELho4nX0h6zS2NAO+HJrx4mhzSUpNFT18E11KC4EVS9TW5iXSEthOzrfBjEU2tvgQKtdJZtFHEy1m8OFZ/OY0GqXzu90VO2IhGrn/CCZ3EJMR20sq8xcKX/c8X27dINTY5ZdePt9l+K0N5QMpebsQXCKws2mQZJfQz28=,iv:c6u50UJZC8xHNAL6xe8nSzLXQ1lNqIKdhJx3HFngv8M=,tag:BftTO/rDR0ztcEXt7jt9jg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
