apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cloudflare-origin-ca-issuer
  namespace: cert-manager
spec:
  interval: 12h
  url: https://github.com/cloudflare/origin-ca-issuer
  ref:
    branch: trunk
