apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-origin-ca-issuer
  namespace: cert-manager
spec:
  interval: 12h
  chart:
    spec:
      chart: deploy/charts/origin-ca-issuer
      sourceRef:
        kind: GitRepository
        name: cloudflare-origin-ca-issuer
  values: {}
